### ISSUE TITLE
Custom Hintergrundfarbe

### ISSUE THREAD

**Issue by Dav-Renz** [bietiekay/Los-Santos-Transit-Bus-Streamer-Display#2]
Wäre es viel Aufwand, auch die Hintergrundfarbe anpassbar zu machen, damit man diese dann raus keyen kann?

**Comment by bietiekay** [comment]
Das ist nicht viel Aufwand. Allerdings kannst du Schwarz ja ebenfalls einfach in OBS keyen?! Jedenfalls geht das bei mir bereits.

**Comment by bietiekay** [comment]
eingebaut in 1.12

**Comment by Dav-Renz** [comment]
Es geht, aber dann sind die nicht aktiven LEDs mit weg verschwunden.
